'use client'

import { useState } from 'react'
import { ArrowUp, Check, Compass, Globe2, Menu, MessageSquarePlus, Paperclip, Plane, Search, Send, Sparkles, Sun, X } from 'lucide-react'
import type { HotelOffer, TravelContext, TravelResponse, TravelResult } from '@/lib/travel/types'

const logoUrl = 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Black%20and%20Orange%20Simple%20Travel%20Agency%20Logo-IycmdZUw0OtRWItkpg7ao73GHSQsNf.png'
const suggestions = [
  { icon: 'sun', title: 'Find a hotel in Rome', prompt: 'Find me a 5-star hotel in Rome for 4 nights under €600.' },
  { icon: 'plane', title: 'Find Cairo → Rome flights', prompt: 'Find flights from Cairo to Rome.' },
  { icon: 'compass', title: 'Plan a week in Italy', prompt: 'Plan a 7-day trip to Italy.' },
  { icon: 'globe', title: 'Find Rome activities', prompt: 'Find things to do in Rome.' },
]
const starterChats = ['Rome hotel search', 'Italy itinerary', 'Cairo to Rome flights']

function Icon({ type }: { type: string }) { const props = { 'aria-hidden': true, className: 'size-4' }; if (type === 'sun') return <Sun {...props} />; if (type === 'compass') return <Compass {...props} />; if (type === 'plane') return <Plane {...props} />; return <Globe2 {...props} /> }

function HotelCard({ offer, onSelect }: { offer: HotelOffer; onSelect: (offer: HotelOffer) => void }) {
  return <article className="overflow-hidden rounded-2xl border border-border bg-card shadow-sm"><img src={offer.image} alt={`${offer.name} exterior`} className="h-36 w-full object-cover" /><div className="flex flex-col gap-3 p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="font-semibold">{offer.name}</h3><p className="mt-1 text-xs text-muted-foreground">{'★'.repeat(offer.stars)} · {offer.location}</p></div><span className="rounded-lg bg-secondary px-2 py-1 text-xs font-semibold">{offer.rating}</span></div><p className="text-xs text-muted-foreground">{offer.roomType} · {offer.amenities.slice(0, 2).join(' · ')}</p><div className="flex items-end justify-between gap-3"><div><p className="text-lg font-bold">€{offer.price.amount}</p><p className="text-[11px] text-muted-foreground">€{offer.pricePerNight}/night · {offer.cancellation}</p></div><button type="button" onClick={() => onSelect(offer)} className="rounded-xl bg-primary px-3 py-2 text-xs font-semibold text-primary-foreground hover:opacity-90">View details</button></div></div></article>
}

function TravelResultCard({ result, onSelect }: { result?: TravelResult; onSelect: (offer: HotelOffer) => void }) {
  if (!result) return null
  if (result.kind === 'hotels') return <div className="mt-4 grid gap-3 sm:grid-cols-2">{result.offers.map((offer) => <HotelCard key={offer.id} offer={offer} onSelect={onSelect} />)}</div>
  if (result.kind === 'flights') return <div className="mt-4 flex flex-col gap-2">{result.offers.map((offer) => <div key={offer.id} className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-border bg-card p-4"><div><p className="font-semibold">{offer.airline}</p><p className="text-sm text-muted-foreground">{offer.route} · {offer.stops} · {offer.duration}</p></div><div className="text-right"><p className="font-bold">€{offer.price.amount}</p><p className="text-xs text-muted-foreground">{offer.departure} → {offer.arrival}</p></div></div>)}</div>
  if (result.kind === 'activities') return <div className="mt-4 grid gap-3 sm:grid-cols-2">{result.offers.map((offer) => <article key={offer.id} className="overflow-hidden rounded-2xl border border-border bg-card"><img src={offer.image} alt={offer.name} className="h-32 w-full object-cover" /><div className="p-4"><h3 className="font-semibold">{offer.name}</h3><p className="mt-1 text-xs text-muted-foreground">{offer.rating} rating · {offer.duration}</p><p className="mt-2 text-sm text-muted-foreground">{offer.description}</p><p className="mt-3 font-bold">€{offer.price.amount}</p></div></article>)}</div>
  if (result.kind === 'itinerary') return <div className="mt-4 flex flex-col gap-2">{result.days.map((day) => <div key={day.day} className="flex gap-3 rounded-2xl border border-border bg-card p-3"><div className="flex size-8 shrink-0 items-center justify-center rounded-full bg-secondary text-xs font-bold">{day.day}</div><div><p className="font-semibold">{day.city} · {day.title}</p><p className="mt-1 text-sm text-muted-foreground">{day.description}</p><div className="mt-2 flex gap-2"><button type="button" className="text-xs font-semibold text-primary">Find hotel</button><button type="button" className="text-xs font-semibold text-primary">Find activities</button></div></div></div>)}</div>
  return null
}

export default function Page() {
  const [sidebarOpen, setSidebarOpen] = useState(false)
  const [input, setInput] = useState('')
  const [messages, setMessages] = useState<Array<{ role: 'user' | 'assistant'; text: string; result?: TravelResult }>>([])
  const [context, setContext] = useState<TravelContext>({})
  const [isThinking, setIsThinking] = useState(false)
  const [selected, setSelected] = useState<HotelOffer | null>(null)

  async function sendMessage(value = input) {
    const trimmed = value.trim(); if (!trimmed || isThinking) return
    setMessages((current) => [...current, { role: 'user', text: trimmed }]); setInput(''); setIsThinking(true)
    try { const response = await fetch('/api/ai/chat', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ message: trimmed, context }) }); const data = await response.json() as TravelResponse; setContext(data.context ?? context); setMessages((current) => [...current, { role: 'assistant', text: data.message, result: data.result }]) } catch { setMessages((current) => [...current, { role: 'assistant', text: 'I couldn’t complete that search right now. Let me try another option.' }]) } finally { setIsThinking(false) }
  }
  function handleKeyDown(event: React.KeyboardEvent<HTMLTextAreaElement>) { if (event.key === 'Enter' && !event.shiftKey && !event.nativeEvent.isComposing && event.keyCode !== 229) { event.preventDefault(); sendMessage() } }

  return <main className="flex min-h-svh bg-background text-foreground">
    <aside className={`fixed inset-y-0 left-0 z-20 flex w-[280px] flex-col border-r border-border bg-sidebar px-3 py-4 transition-transform duration-200 lg:static lg:translate-x-0 ${sidebarOpen ? 'translate-x-0' : '-translate-x-full'}`}>
      <div className="flex items-center justify-between px-2 pb-5"><a href="#" className="flex items-center gap-2" aria-label="BEKA home"><img src={logoUrl} alt="BEKA — Your AI Travel Agent" className="h-10 w-16 object-contain object-top" /><span className="font-mono text-sm font-bold tracking-[0.22em]">BEKA</span></a><button type="button" onClick={() => setSidebarOpen(false)} className="rounded-lg p-2 text-muted-foreground hover:bg-accent lg:hidden" aria-label="Close navigation"><X className="size-4" /></button></div>
      <button type="button" onClick={() => { setMessages([]); setContext({}); setSidebarOpen(false) }} className="flex items-center gap-3 rounded-xl border border-border bg-background px-3 py-2.5 text-sm font-medium shadow-sm hover:bg-accent"><MessageSquarePlus className="size-4 text-primary" /> New chat <span className="ml-auto text-xs text-muted-foreground">⌘ K</span></button>
      <nav className="mt-6 flex flex-col gap-1" aria-label="Main navigation"><a className="flex items-center gap-3 rounded-xl bg-accent px-3 py-2.5 text-sm font-medium" href="#"><Sparkles className="size-4 text-primary" /> Ask BEKA</a><a className="flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm text-muted-foreground hover:bg-accent hover:text-foreground" href="#explore"><Compass className="size-4" /> Explore</a><a className="flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm text-muted-foreground hover:bg-accent hover:text-foreground" href="#trips"><Plane className="size-4" /> My trips</a></nav>
      <div className="mt-8 flex flex-col gap-2"><p className="px-3 text-[11px] font-semibold uppercase tracking-[0.18em] text-muted-foreground">Recent chats</p>{starterChats.map((chat) => <button key={chat} type="button" onClick={() => setInput(`Continue planning ${chat}`)} className="truncate rounded-xl px-3 py-2 text-left text-sm text-muted-foreground hover:bg-accent hover:text-foreground">{chat}</button>)}</div>
      <div className="mt-auto rounded-2xl border border-border bg-background p-3"><p className="text-xs font-semibold">Travel, thoughtfully planned.</p><p className="mt-1 text-xs leading-5 text-muted-foreground">Mock inventory is clearly labelled. BEKA never pretends a result is live.</p></div>
    </aside>
    {sidebarOpen && <button type="button" aria-label="Close navigation overlay" onClick={() => setSidebarOpen(false)} className="fixed inset-0 z-10 bg-foreground/20 lg:hidden" />}
    <section className="flex min-w-0 flex-1 flex-col"><header className="flex h-16 items-center justify-between border-b border-border px-4 sm:px-6"><div className="flex items-center gap-3"><button type="button" onClick={() => setSidebarOpen(true)} className="rounded-lg p-2 hover:bg-accent lg:hidden" aria-label="Open navigation"><Menu className="size-5" /></button><div className="flex items-center gap-2"><span className="font-mono text-sm font-bold tracking-[0.18em]">Ask BEKA</span><span className="rounded-full bg-primary/10 px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wider text-primary">Travel AI</span></div></div><div className="flex items-center gap-1"><button type="button" className="rounded-lg p-2 text-muted-foreground hover:bg-accent" aria-label="Search chats"><Search className="size-4" /></button><button type="button" className="rounded-lg p-2 text-muted-foreground hover:bg-accent" aria-label="Toggle theme"><Sun className="size-4" /></button><div className="ml-2 flex size-8 items-center justify-center rounded-full bg-primary text-xs font-bold text-primary-foreground">A</div></div></header>
      <div className="flex min-h-0 flex-1 flex-col"><div className="mx-auto flex w-full max-w-4xl flex-1 flex-col px-4 pb-36 pt-10 sm:px-8">{messages.length === 0 ? <div className="flex flex-1 flex-col items-center justify-center pb-10 text-center"><img src={logoUrl} alt="BEKA" className="mb-5 h-28 w-48 object-contain object-top" /><h1 className="font-mono text-2xl font-bold tracking-tight sm:text-3xl">Where will you go?</h1><p className="mt-3 max-w-md text-sm leading-6 text-muted-foreground">Your AI travel agent for ideas, itineraries, and thoughtfully selected options.</p><div className="mt-8 grid w-full max-w-xl grid-cols-1 gap-2 sm:grid-cols-2">{suggestions.map((suggestion) => <button key={suggestion.title} type="button" onClick={() => sendMessage(suggestion.prompt)} className="group flex items-center gap-3 rounded-2xl border border-border bg-card p-3 text-left hover:border-primary/40 hover:bg-accent"><span className="flex size-8 shrink-0 items-center justify-center rounded-xl bg-secondary text-primary"><Icon type={suggestion.icon} /></span><span className="min-w-0"><span className="block text-sm font-medium">{suggestion.title}</span><span className="block truncate text-xs text-muted-foreground">{suggestion.prompt}</span></span><ArrowUp className="ml-auto size-4 rotate-45 text-muted-foreground opacity-0 group-hover:opacity-100" /></button>)}</div></div> : <div className="flex flex-col gap-8">{messages.map((message, index) => <div key={`${message.role}-${index}`} className={`flex gap-3 ${message.role === 'user' ? 'justify-end' : 'justify-start'}`}><div className={`max-w-full ${message.role === 'user' ? 'rounded-2xl rounded-br-md bg-primary px-4 py-3 text-primary-foreground sm:max-w-[80%]' : 'flex w-full gap-3'}`}>{message.role === 'assistant' && <div className="mt-1 flex size-7 shrink-0 items-center justify-center rounded-full bg-secondary"><Sparkles className="size-3.5 text-primary" /></div>}<div className="min-w-0 flex-1"><p className="text-sm leading-7">{message.text}</p><TravelResultCard result={message.result} onSelect={setSelected} /></div></div></div>)}{isThinking && <div className="flex items-center gap-3 text-sm text-muted-foreground"><div className="flex size-7 items-center justify-center rounded-full bg-secondary"><Sparkles className="size-3.5 text-primary" /></div><span className="thinking-dots">BEKA is searching travel options</span></div>}</div>}</div>
      <div className="fixed inset-x-0 bottom-0 bg-gradient-to-t from-background via-background to-transparent px-4 pb-4 pt-10 sm:px-8 lg:left-[280px]"><form onSubmit={(event) => { event.preventDefault(); sendMessage() }} className="mx-auto max-w-4xl"><div className="flex items-end gap-2 rounded-2xl border border-border bg-card p-2 shadow-lg shadow-foreground/5 focus-within:border-primary/50"><button type="button" className="mb-0.5 rounded-xl p-2.5 text-muted-foreground hover:bg-accent" aria-label="Attach a file"><Paperclip className="size-4" /></button><textarea value={input} onChange={(event) => setInput(event.target.value)} onKeyDown={handleKeyDown} placeholder="Where do you want to go?" rows={1} className="max-h-32 min-h-10 flex-1 resize-none bg-transparent px-1 py-2.5 text-sm outline-none placeholder:text-muted-foreground" aria-label="Message BEKA" /><button type="submit" disabled={!input.trim() || isThinking} className="mb-0.5 flex size-9 items-center justify-center rounded-xl bg-primary text-primary-foreground hover:opacity-90 disabled:opacity-40" aria-label="Send message"><Send className="size-4" /></button></div><p className="mt-2 text-center text-[11px] text-muted-foreground">BEKA uses development mock results. Check important travel details before booking.</p></form></div></div></section>
    {selected && <div role="dialog" aria-modal="true" aria-label="Hotel details" className="fixed inset-0 z-30 flex items-end justify-center bg-foreground/30 p-4 sm:items-center"><div className="w-full max-w-md rounded-3xl border border-border bg-card p-5 shadow-xl"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-wider text-primary">BEKA'S PICK</p><h2 className="mt-1 text-xl font-bold">{selected.name}</h2><p className="mt-1 text-sm text-muted-foreground">{selected.recommendation}</p></div><button type="button" onClick={() => setSelected(null)} aria-label="Close hotel details" className="rounded-lg p-2 hover:bg-accent"><X className="size-4" /></button></div><div className="mt-5 flex flex-col gap-3 text-sm"><div className="flex items-center gap-2"><Check className="size-4 text-primary" /> {selected.cancellation}</div><div className="flex items-center gap-2"><Check className="size-4 text-primary" /> {selected.amenities.join(' · ')}</div><div className="rounded-2xl bg-secondary p-3 text-xs text-secondary-foreground">This is a mock offer. Price check and booking are not connected yet.</div></div><button type="button" onClick={() => setSelected(null)} className="mt-5 w-full rounded-xl bg-primary px-4 py-3 text-sm font-semibold text-primary-foreground">Continue to booking review</button></div></div>}
  </main>
}
